### ISSUE TITLE
Controllers

### ISSUE THREAD

**Issue by gokaygurcan** [Adyen/adyen-demandware#3]
Do you have any plan to convert your pipelines to controllers? If so, could you please share the timeframe?

Thanks

**Comment by gokaygurcan** [comment]
![image](https://cloud.githubusercontent.com/assets/1509413/19410386/b31cdf0a-92f3-11e6-84a8-b06112dacf21.png)

**Comment by HugoTrimp** [comment]
Thanks for reaching out.

Indeed we are working on an updated version of the cartridge which leverages the controllers approach. We expect the new cartridge to become available within 8 weeks from now.

**Comment by gokaygurcan** [comment]
Hello @HugoTrimp,

Thanks for the reply. This is a great news! Looking forward to work with the controllers in our project(s).
